feat: add Story Testnet
hyperlane-xyz/hyperlane-registry pull request #264
Opened 2024-10-08 15:34 UTC by atuser14

### Description
There is missing the trendy story testnet ,so i request to add this to hyperlane registry.

### Backward compatibility

no
### Testing
yes

2024-10-09 17:29 UTC, jmrossy commented on chains/storytestnet/logo.svg
Can you please remove the white background around the edges?

2024-10-09 17:55 UTC, atuser14 commented on chains/storytestnet/logo.svg
i removed the white background,thanks for the review.

2024-10-10 17:58 UTC, jmrossy commented on chains/storytestnet/logo.svg
Are you sure? There's a white rectangle in the bottom-right

2024-10-15 20:55 UTC, xeno097 requested changes

2024-10-15 20:55 UTC, xeno097 commented on chains/storytestnet/addresses.yaml
> +TransparentUpgradeableProxy: "0x4E14A4a64A9eEC00EB773891562BABFE3B824530"
Hey @atuser14 thank you for your PR to the Hyperlane Registry! Could you please remove the `TransparentUpgradeableProxy` field from this file? After that run `yarn lint --fix` to properly format the file and have the fields in the expected order. 

Finally sync your branch with the main branch to be sure that the ci runs on the latest version of the changes

2024-10-16 14:40 UTC, jmrossy commented
As JaunePomme said, you need to run `yarn prettier` to fix the formatting issue with your addresses file

2024-10-16 17:09 UTC, xeno097 approved these changes

2024-10-16 17:15 UTC, merged