Add CheeseChain
hyperlane-xyz/hyperlane-registry pull request #270
Opened 2024-10-10 03:35 UTC by bivsk

### Description

Add CheeseChain

### Backward compatibility

Yes

2024-10-10 18:03 UTC, jmrossy requested changes
A few problems here:
1) if the route is cheesechain <-> arbitrum, it should not be changing this existing cheesechain <-> ethereum file
2) The PR title is inaccurate  
3) You're missing a changeset (run `yarn changeset`)

2024-10-10 19:44 UTC, bivsk commented
Regarding 1, we do not want to support the old cheesechain <-> ethereum route any longer. Can I just rename this current file?

2024-10-10 19:45 UTC, rshtirmer commented
> A few problems here:
> 
> 1. if the route is cheesechain <-> arbitrum, it should not be changing this existing cheesechain <-> ethereum file
> 2. The PR title is inaccurate
> 3. You're missing a changeset (run `yarn changeset`)

Hey J,

I published the original route that @bivsk is overwriting - that route being overwritten is deprecated, and does not point to what is now the canonical USDC on cheesechain (which is created by bridging USDC from arb -> cheesechain via this new route)  - @bivsk will add a changeset, but otherwise I think this should be ok? Please let me know if theres anything else we can do to support. 

Best,
Ryan Shtirmer

2024-10-12 02:17 UTC, bivsk commented
@jmrossy I've made a few changes to hopefully fix the above issues, while also sticking to our plan to replace rather than add a route.  Hopefully this works, but let me know if not.  Thanks a lot, and have a good rest of your weekend

2024-10-16 14:29 UTC, jmrossy reviewed
Almost there!

2024-10-16 14:29 UTC, jmrossy commented on .changeset/chilled-yaks-nail.md
> +'@hyperlane-xyz/registry': patch
```suggestion
'@hyperlane-xyz/registry': major
```

2024-10-16 14:29 UTC, jmrossy commented on .changeset/chilled-yaks-nail.md
> +'@hyperlane-xyz/registry': patch
Whenever something is removed, that's a breaking change and the version increment will need to be `major`

2024-10-16 14:29 UTC, jmrossy commented on deployments/warp_routes/USDC/cheesechain-arbitrum-config.yaml
Ditto above for filename

2024-10-16 14:29 UTC, jmrossy commented on deployments/warp_routes/USDC/cheesechain-arbitrum-addresses.yaml
The filename is now incorrect. The chains should be alphabetically ordered (arbitrum-cheesechain).

2024-10-16 14:52 UTC, bivsk commented
OK pretty sure it's all good to go now 😅

Thanks again!

2024-10-20 16:50 UTC, jmrossy commented
@bivsk Still one more problem. run `yarn lint:fix`

<img width="1378" alt="Screenshot 2024-10-20 at 12 50 18 PM" src="https://github.com/user-attachments/assets/87f03cf3-0e9c-45d4-b95a-66bc92813e8e">

2024-10-21 16:36 UTC, jmrossy approved these changes

2024-10-21 16:36 UTC, merged