Added echos chain and INTERN warp route
hyperlane-xyz/hyperlane-registry pull request #432
Opened 2024-12-16 18:25 UTC by sampocs

### Description
Added echos chain and INTERN warp route to inEVM

### Backward compatibility
Yes

### Testing
Addresses pulled from CLI during deployment.

2024-12-17 16:18 UTC, paulbalaji reviewed
pls run `yarn lint:fix` and `yarn prettier` from repo root

2024-12-17 16:18 UTC, paulbalaji commented on deployments/warp_routes/INTERN/logo.svg
could we get a smaller svg please 🙏

2024-12-17 16:18 UTC, paulbalaji commented on chains/echos/logo.svg
please crop / minimise
- crop https://svgcrop.com/
- minimise https://jakearchibald.github.io/svgomg/

2024-12-17 19:15 UTC, sampocs commented on deployments/warp_routes/INTERN/logo.svg
what size should I target? Just cropped and minimized, but lmk if it's still too big

2024-12-17 19:15 UTC, sampocs commented on chains/echos/logo.svg
done https://github.com/hyperlane-xyz/hyperlane-registry/pull/432/commits/00f1b2a61bc6bf5add5f83dd98502dbbaf11d4b8

2024-12-18 15:40 UTC, paulbalaji commented on chains/echos/metadata.yaml
> +domainId: 2525
typo? 
```suggestion
domainId: 4321
```

2024-12-18 15:59 UTC, paulbalaji approved these changes

2024-12-18 16:04 UTC, jmrossy requested changes

2024-12-18 16:04 UTC, jmrossy commented on deployments/warp_routes/INTERN/logo.svg
You can use a jpg or png here and it would get you better quality in a smaller size. 
Also the image won't look good when cropped to a circle

2024-12-18 16:04 UTC, jmrossy commented on .changeset/odd-boats-attend.md
> +"@hyperlane-xyz/registry": patch
```suggestion
"@hyperlane-xyz/registry": minor
```

2024-12-18 16:12 UTC, paulbalaji commented on .changeset/odd-boats-attend.md
> +"@hyperlane-xyz/registry": patch
```suggestion
"@hyperlane-xyz/registry": minor
```

2024-12-18 17:15 UTC, merged