Add new Renzo warp route
hyperlane-xyz/hyperlane-registry pull request #93
Opened 2024-07-09 19:21 UTC by nambrot

### Description

New "updated" warp route for Renzo's ezETH

#### Type: <Updated> <Warp Route>

2024-07-09 19:37 UTC, ltyu approved these changes

2024-07-09 20:02 UTC, nbayindirli approved these changes
like we did [here](https://github.com/hyperlane-xyz/hyperlane-warp-ui-template/pull/196/files) can we scrub the [old warp route](https://github.com/hyperlane-xyz/hyperlane-registry/blob/main/deployments/warp_routes/EZETH/arbitrum-base-blast-bsc-ethereum-linea-mode-optimism-config.yaml) of the unnecessary fields?

otherwise lgtm

2024-07-09 22:20 UTC, jmrossy commented
Changeset

2024-07-09 22:20 UTC, jmrossy requested changes
Changeset

2024-07-10 15:10 UTC, jmrossy approved these changes

2024-07-10 16:11 UTC, merged